<#
.SYNOPSIS
    launch_viewer.ps1 - Pure Windows Native Image Metadata Viewer Launcher
    Zero Node.js dependency. Opens images and folder contents directly in viewer.html.
#>

param(
    [Parameter(ValueFromRemainingArguments = $true)]
    [string[]]$Paths
)

$ErrorActionPreference = 'Stop'
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$viewerHtml = Join-Path $scriptDir "viewer.html"
$sessionJs = Join-Path $scriptDir "session_data.js"

# If no arguments provided, launch viewer.html directly in clean mode
if (-not $Paths -or $Paths.Count -eq 0) {
    Write-Host "================================================================" -ForegroundColor Yellow
    Write-Host "  Nano Banana Ultra - 圖片中繼資料檢視器 (Metadata Viewer)" -ForegroundColor Yellow
    Write-Host "================================================================" -ForegroundColor Yellow
    Write-Host "  提示: 可直接將圖片 (.png / .jpg) 或整個資料夾拖曳至此批次檔！"
    Write-Host "  正在為您開啟空白檢視器..." -ForegroundColor Cyan
    Write-Host "================================================================" -ForegroundColor Yellow
    Start-Process $viewerHtml
    exit 0
}

# Collect valid image files (.png, .jpg, .jpeg) from passed files or folders
$imageFiles = [System.Collections.Generic.List[System.IO.FileInfo]]::new()

foreach ($p in $Paths) {
    if (-not $p) { continue }
    $cleanPath = $p.Trim('"')

    if (Test-Path -LiteralPath $cleanPath -PathType Container) {
        $found = Get-ChildItem -LiteralPath $cleanPath -File | Where-Object { $_.Extension -match '^\.(png|jpe?g)$' }
        foreach ($f in $found) {
            $imageFiles.Add($f)
        }
    } elseif (Test-Path -LiteralPath $cleanPath -PathType Leaf) {
        $item = Get-Item -LiteralPath $cleanPath
        if ($item.Extension -match '^\.(png|jpe?g)$') {
            $imageFiles.Add($item)
        }
    }
}

if ($imageFiles.Count -eq 0) {
    Write-Host "❌ [警告] 未在傳入的路徑中找到任何支援的 PNG 或 JPEG 圖片檔案。" -ForegroundColor Red
    Write-Host "請確認拖曳的檔案為 .png 或 .jpg / .jpeg 格式。"
    Start-Sleep -Seconds 2
    exit 1
}

Write-Host "================================================================" -ForegroundColor Green
Write-Host "  Nano Banana Ultra - 圖片中繼資料檢視器 (Metadata Viewer)" -ForegroundColor Green
Write-Host "================================================================" -ForegroundColor Green
Write-Host "  ✓ 已成功讀取 $($imageFiles.Count) 個圖片檔案，正在瀏覽器中開啟檢視器..." -ForegroundColor Cyan
Write-Host "================================================================" -ForegroundColor Green

# Convert images to Base64 Data URLs
$sessionList = [System.Collections.Generic.List[PSObject]]::new()

foreach ($file in $imageFiles) {
    $bytes = [System.IO.File]::ReadAllBytes($file.FullName)
    $b64 = [System.Convert]::ToBase64String($bytes)
    $ext = $file.Extension.ToLower()
    $mime = if ($ext -eq '.png') { 'image/png' } else { 'image/jpeg' }

    $sessionList.Add([PSCustomObject]@{
        name = $file.Name
        mime = $mime
        data = "data:$mime;base64,$b64"
    })
}

# Ensure single-item arrays are correctly formatted as JSON arrays
$imagesJson = if ($sessionList.Count -eq 1) {
    "[" + ($sessionList[0] | ConvertTo-Json -Compress) + "]"
} else {
    ($sessionList | ConvertTo-Json -Compress)
}

$timestamp = [DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()

# Write session_data.js
$jsContent = "// Auto-generated by launch_viewer.ps1`nwindow.__DROP_SESSION__ = { timestamp: $timestamp, images: $imagesJson };"
[System.IO.File]::WriteAllText($sessionJs, $jsContent, [System.Text.Encoding]::UTF8)

# Launch default browser with file:/// URI and #drop hash
$viewerUri = "file:///$($viewerHtml.Replace('\', '/'))#drop"
Start-Process $viewerUri

# Brief pause for user feedback before closing window
Start-Sleep -Milliseconds 400
exit 0
